# coding: utf-8

"""
    L3vels Api

    L3vels API for Game developers  # noqa: E501

    The version of the OpenAPI document: 0.3
    Contact: support@l3vels.xyz
    Generated by: https://openapi-generator.tech
"""

from l3vels.paths.v1_asset_count_game_id.get import CountByGame
from l3vels.paths.v1_asset.post import CreateAsset
from l3vels.paths.v1_asset_game_id_id.get import GetAssetById
from l3vels.paths.v1_asset.get import GetAssets
from l3vels.paths.v1_asset_id.patch import UpdateAsset


class AssetApi(
    CountByGame,
    CreateAsset,
    GetAssetById,
    GetAssets,
    UpdateAsset,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
