# coding: utf-8

"""
    L3vels Api

    L3vels API for Game developers  # noqa: E501

    The version of the OpenAPI document: 0.3
    Contact: support@l3vels.xyz
    Generated by: https://openapi-generator.tech
"""

from l3vels.paths.v1_collection_project_id_id.get import CollectionControllerCollectionById
from l3vels.paths.v1_collection.get import CollectionControllerCollections
from l3vels.paths.v1_collection_count_project_id.get import CollectionControllerCollectionsCountByGameId


class CollectionApi(
    CollectionControllerCollectionById,
    CollectionControllerCollections,
    CollectionControllerCollectionsCountByGameId,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
