# coding: utf-8

"""
    L3vels Api

    L3vels API for Game developers  # noqa: E501

    The version of the OpenAPI document: 0.3
    Contact: support@l3vels.xyz
    Generated by: https://openapi-generator.tech
"""

from l3vels.paths.v1_contract_collection_size.get import ContractControllerCollectionSize
from l3vels.paths.v1_contract_contract_uri.get import ContractControllerContractUri
from l3vels.paths.v1_contract_contract_uri.put import ContractControllerSetContractUri
from l3vels.paths.v1_contract_sale_status.put import ContractControllerSetSaleStatus


class ContractApi(
    ContractControllerCollectionSize,
    ContractControllerContractUri,
    ContractControllerSetContractUri,
    ContractControllerSetSaleStatus,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
