# coding: utf-8

"""
    L3vels Api

    L3vels API for Game developers  # noqa: E501

    The version of the OpenAPI document: 0.3
    Contact: support@l3vels.xyz
    Generated by: https://openapi-generator.tech
"""

from l3vels.paths.v1_mint_airdrop.post import AirdropAssetToPlayer
from l3vels.paths.v1_mint_award.post import AwardAssetToPlayer
from l3vels.paths.v1_mint_batch_player.post import BatchMintAssetByPlayer
from l3vels.paths.v1_mint.post import MintAsset
from l3vels.paths.v1_mint_player.post import MintAssetByPlayer
from l3vels.paths.v1_mint_batch.post import MintBatchAsset


class MintApi(
    AirdropAssetToPlayer,
    AwardAssetToPlayer,
    BatchMintAssetByPlayer,
    MintAsset,
    MintAssetByPlayer,
    MintBatchAsset,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
