# coding: utf-8

"""
    L3vels Api

    L3vels API for Game developers  # noqa: E501

    The version of the OpenAPI document: 0.3
    Contact: support@l3vels.xyz
    Generated by: https://openapi-generator.tech
"""

from l3vels.paths.v1_transaction_game_id_id.get import GetTransactionById
from l3vels.paths.v1_transaction.get import GetTransactions
from l3vels.paths.v1_transaction_webhook.post import TransactionControllerWebhook


class TransactionApi(
    GetTransactionById,
    GetTransactions,
    TransactionControllerWebhook,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
