# coding: utf-8

"""
    L3vels Api

    L3vels API for Game developers  # noqa: E501

    The version of the OpenAPI document: 0.3
    Contact: support@l3vels.xyz
    Generated by: https://openapi-generator.tech
"""

import unittest

import l3vels
from l3vels.model.assets_response_dto import AssetsResponseDto
from l3vels import configuration


class TestAssetsResponseDto(unittest.TestCase):
    """AssetsResponseDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
